const TRANSICIONES = {
  PENDIENTE: {
    OPERADOR: ['VISUALIZADO', 'RECHAZADO'],
    ALCALDIA: ['VISUALIZADO', 'RECHAZADO']
  },
  VISUALIZADO: {
    OPERADOR: ['ASIGNADO', 'RECHAZADO'],
    ALCALDIA: ['ASIGNADO', 'RECHAZADO'],
    FUNCIONARIO: ['EN_PROCESO']
  },
  ASIGNADO: {
    FUNCIONARIO: ['EN_PROCESO'],
    ALCALDIA: ['EN_PROCESO', 'VISUALIZADO', 'RECHAZADO']
  },
  EN_PROCESO: {
    FUNCIONARIO: ['EN_ESPERA', 'RESUELTO'],
    ALCALDIA: ['RESUELTO']
  },
  EN_ESPERA: {
    FUNCIONARIO: ['EN_PROCESO', 'RESUELTO'],
    ALCALDIA: ['RESUELTO']
  }
};

module.exports = TRANSICIONES;