const TRANSICIONES = {
  PENDIENTE: {
    OPERADOR: ['EN_PROCESO', 'RECHAZADO'],
    ALCALDIA: ['EN_PROCESO', 'RECHAZADO']
  },
  EN_PROCESO: {
    FUNCIONARIO: ['EN_ESPERA', 'RESUELTO'],
    ALCALDIA: ['RESUELTO']
  },
  EN_ESPERA: {
    FUNCIONARIO: ['EN_PROCESO', 'RESUELTO'],
    ALCALDIA: ['RESUELTO']
  }
};

module.exports = TRANSICIONES;
