const TRANSICIONES = {
  PENDIENTE: {
    OPERADOR:    ['EN_PROCESO', 'RECHAZADO'],
    ALCALDIA:    ['EN_PROCESO', 'RECHAZADO'],
    ADMIN:       ['EN_PROCESO', 'RECHAZADO'],
    SUPERVISOR:  ['EN_PROCESO', 'RECHAZADO']
  },
  EN_PROCESO: {
    FUNCIONARIO: ['EN_ESPERA', 'RESUELTO'],
    ALCALDIA:    ['RESUELTO'],
    ADMIN:       ['EN_ESPERA', 'RESUELTO', 'RECHAZADO'],
    SUPERVISOR:  ['EN_ESPERA', 'RESUELTO', 'RECHAZADO']
  },
  EN_ESPERA: {
    FUNCIONARIO: ['EN_PROCESO', 'RESUELTO'],
    ALCALDIA:    ['RESUELTO'],
    ADMIN:       ['EN_PROCESO', 'RESUELTO', 'RECHAZADO'],
    SUPERVISOR:  ['EN_PROCESO', 'RESUELTO', 'RECHAZADO']
  },
  RESUELTO: {
    ADMIN:       ['PENDIENTE'],
    SUPERVISOR:  ['PENDIENTE']
  },
  RECHAZADO: {
    ADMIN:       ['PENDIENTE'],
    SUPERVISOR:  ['PENDIENTE']
  }
};

module.exports = TRANSICIONES;